# Generated by Django 5.0.2 on 2024-03-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_cloth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='phone',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='car_dealer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='cloth',
            old_name='type',
            new_name='username',
        ),
    ]
